import Image from 'next/image';
import { HERO_WALL_A, HERO_WALL_B, type Creative } from '@/lib/creatives';
import { CAL_URL } from '@/lib/site';
import styles from './Hero.module.css';

/* Each column renders its set twice: the drift animation translates the
   column by -50%, so the duplicate makes the loop wrap seamlessly. */
function WallColumn({ ads, className }: { ads: Creative[]; className: string }) {
  return (
    <div className={className}>
      {[false, true].map((isDupe) =>
        ads.map((ad) => (
          <Image
            key={`${ad.src}${isDupe ? '-dupe' : ''}`}
            src={ad.src}
            alt={isDupe ? '' : ad.alt}
            width={ad.width}
            height={ad.height}
            aria-hidden={isDupe || undefined}
            loading={isDupe ? 'lazy' : undefined}
            className={styles.wallAd}
          />
        )),
      )}
    </div>
  );
}

export function Hero() {
  return (
    <header id="top" className={styles.hero}>
      <div className={styles.grid}>
        <div className={styles.copy}>
          <div className={styles.pill}>for brands and agencies running Meta ads</div>
          <h1 className={styles.h1}>
            Paste your URL. Get Meta ads that <span className={styles.h1Accent}>actually look like your brand.</span>
          </h1>
          <p className={styles.sub}>
            Loopy reads your website and turns proven ad layouts into finished Meta ads that match it: your colors,
            your fonts, your real product. No designer, no prompting.
          </p>
          <div className={styles.ctaRow}>
            <a href={CAL_URL} className={styles.cta}>
              see it run on your brand <span aria-hidden="true">↗</span>
            </a>
          </div>
          <p className={styles.fineprint}>
            20 minutes with the founders - <b>first 10 ads free, on your real brand</b> - no card
          </p>
        </div>
        <div className={styles.adWall} aria-label="A wall of demo ads generated by Loopy">
          <div className={styles.wallGrid}>
            <WallColumn ads={HERO_WALL_A} className={styles.colUp} />
            <WallColumn ads={HERO_WALL_B} className={styles.colDown} />
          </div>
          <span className={styles.demoLabel}>demo reskins - not customers</span>
        </div>
      </div>
    </header>
  );
}
