export interface Creative { src: string; alt: string; }
export interface BrandSet { brand: string; label: string; ads: Creative[]; }

/** Build a brand's ad list. Pass a count for sequential ad-01..0N, or an
 *  explicit list of indices (e.g. to skip a weak creative). */
const ads = (brand: string, nOrIdx: number | number[], label: string): Creative[] => {
  const idx = Array.isArray(nOrIdx) ? nOrIdx : Array.from({ length: nOrIdx }, (_, i) => i + 1);
  return idx.map((i) => ({
    src: `/creatives/${brand}/ad-0${i}.jpg`,
    alt: `${label} ad creative — generated by BetterYourAds`,
  }));
};

/** The brand threaded through how-it-works (the pipeline worked example). */
export const WORKED_EXAMPLE: BrandSet = { brand: 'notion', label: 'Notion', ads: ads('notion', 4, 'Notion') };

/** The brand shown fanning out in the hero Batch Cascade — one Zoom Workplace
 *  reference (ads[0]) → four hand-picked on-brand variations. Kept distinct from
 *  WORKED_EXAMPLE and the wall so no creative repeats across sections. */
export const HERO_BRAND: BrandSet = {
  brand: 'zoom',
  label: 'Zoom',
  ads: [
    { src: '/creatives/zoom/ref.jpg', alt: 'Zoom Workplace reference ad — “Designed for how you actually work”' },
    { src: '/creatives/zoom/v1.png', alt: 'Zoom Workplace ad — “Built-in AI. No extra cost.” — generated by BetterYourAds' },
    { src: '/creatives/zoom/v2.png', alt: 'Zoom Workplace ad — “Trusted by millions. 4.5/5 stars.” — generated by BetterYourAds' },
    { src: '/creatives/zoom/v3.png', alt: 'Zoom Workplace ad — “Dream workflow achieved.” — generated by BetterYourAds' },
    { src: '/creatives/zoom/v4.png', alt: 'Zoom Workplace ad — “Emmy-winning engineering.” — generated by BetterYourAds' },
  ],
};

/** Recognizable brands for the Living Wall — proves range. Excludes the hero
 *  (Zoom) and pipeline (Notion) brands so nothing appears twice. Counts match
 *  disk; Zapier skips ad-03 (a weak creative). */
export const WALL_BRANDS: BrandSet[] = [
  { brand: 'slack',       label: 'Slack',       ads: ads('slack',       4, 'Slack') },
  { brand: 'asana',       label: 'Asana',       ads: ads('asana',       3, 'Asana') },
  { brand: 'monday-com',  label: 'monday.com',  ads: ads('monday-com',  2, 'monday.com') },
  { brand: 'clickup',     label: 'ClickUp',     ads: ads('clickup',     3, 'ClickUp') },
  { brand: 'zapier',      label: 'Zapier',      ads: ads('zapier',  [1, 2, 4], 'Zapier') },
  { brand: 'grammarly',   label: 'Grammarly',   ads: ads('grammarly',   2, 'Grammarly') },
  { brand: 'mailchimp',   label: 'Mailchimp',   ads: ads('mailchimp',   2, 'Mailchimp') },
  { brand: 'gusto',       label: 'Gusto',       ads: ads('gusto',       3, 'Gusto') },
  { brand: 'kinsta',      label: 'Kinsta',      ads: ads('kinsta',      3, 'Kinsta') },
];

export const allWallAds = (): Creative[] => WALL_BRANDS.flatMap((b) => b.ads);
