export interface Creative { src: string; alt: string; }
export interface BrandSet { brand: string; label: string; ads: Creative[]; }

const ads = (brand: string, n: number, label: string): Creative[] =>
  Array.from({ length: n }, (_, i) => ({
    src: `/creatives/${brand}/ad-0${i + 1}.jpg`,
    alt: `${label} ad creative — generated by BetterYourAds`,
  }));

/** The single brand threaded through hero + how-it-works (the worked example). */
export const WORKED_EXAMPLE: BrandSet = { brand: 'notion', label: 'Notion', ads: ads('notion', 4, 'Notion') };

/** Recognizable brands for the Living Wall — proves range. Counts match disk. */
export const WALL_BRANDS: BrandSet[] = [
  { brand: 'slack',       label: 'Slack',       ads: ads('slack',       4, 'Slack') },
  { brand: 'asana',       label: 'Asana',       ads: ads('asana',       3, 'Asana') },
  { brand: 'monday-com',  label: 'monday.com',  ads: ads('monday-com',  2, 'monday.com') },
  { brand: 'clickup',     label: 'ClickUp',     ads: ads('clickup',     3, 'ClickUp') },
  { brand: 'zapier',      label: 'Zapier',      ads: ads('zapier',      4, 'Zapier') },
  { brand: 'grammarly',   label: 'Grammarly',   ads: ads('grammarly',   2, 'Grammarly') },
  { brand: 'mailchimp',   label: 'Mailchimp',   ads: ads('mailchimp',   2, 'Mailchimp') },
  { brand: 'gusto',       label: 'Gusto',       ads: ads('gusto',       3, 'Gusto') },
  { brand: 'kinsta',      label: 'Kinsta',      ads: ads('kinsta',      3, 'Kinsta') },
];

export const allWallAds = (): Creative[] => WALL_BRANDS.flatMap((b) => b.ads);
